spring:
  profiles:
    active: dev
server:
  port: 8580
  servlet:
    context-path: /romeole
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

---
spring:
  profiles: dev

---
spring:
  profiles: pro
